name: test-check

on: push
jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          pip install pytest
          make install
      - name: test application
        run: make test