name: test-check

on: push
jobs:
  tests-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          pip install pytest
          make install
      - name: test application
        run: make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 6a31547eadce6a0a77a2aecb3da830777e0e3f413c718101b113823c97aa0530
        with:
          coverageCommand: make test-coverage
          debug: true